fix bug: failed to git clone docker-containerd
PelionIoT/snap-pelion-edge pull request #330
Opened 2021-01-06 17:54 UTC by costanic

One of the repos cloned by the build process contains Windows
line endings and depending on the local user's git config may
cause further clone failures.  By forcing autocrlf to false,
we preserve the original files so that they show unmodified.

2021-01-06 23:41 UTC, ryannowarm requested changes
somehow doing this changed my `snap-pelion-edge/.git/config` file to be owned by root:root.  I don't think we want that, right?

2021-01-07 12:11 UTC, OPpuolitaival approved these changes

2021-01-07 14:28 UTC, mohitsingalarm approved these changes
Thanks Nic for the fix. Please update the jira once merged : https://armiot.atlassian.net/browse/PELEDGE19-3894

2021-01-07 14:51 UTC, costanic commented
> somehow doing this changed my `snap-pelion-edge/.git/config` file to be owned by root:root. I don't think we want that, right?

Interesting, although I do see how this modifies the wrong user's git-config.  It should be modifying "user" gitconfig, not the caller's gitconfig (i.e., /home/user/.gitconfig).

2021-01-07 21:15 UTC, mray190 approved these changes

2021-01-07 22:34 UTC, costanic commented
@ryannowarm does this newer PR work for you?

2021-01-08 18:25 UTC, ryannowarm commented
Re-running build test now

2021-01-08 18:31 UTC, ryannowarm commented
Build works for me.  Looks good.

2021-01-08 18:32 UTC, ryannowarm approved these changes

2021-01-08 19:17 UTC, merged