Add PR check to sure that base branch is dev
PelionIoT/snap-pelion-edge pull request #394
Opened 2021-08-12 21:53 UTC by ryannowarm

We've had some issues accidentally merging PRs against master.  By
default all PRs should be against dev branch.  This github action should
ensure that.

2021-08-12 23:25 UTC, costanic requested changes
How do we make an exception for [release PRs](https://github.com/PelionIoT/snap-pelion-edge/pull/386)?  It would be nice if we could show clean status when we merge those.

2021-08-12 23:29 UTC, ryannowarm commented
I could add an exception that if the source branch is dev then the base(target) branch can be master.

2021-08-13 12:03 UTC, costanic commented
> I could add an exception that if the source branch is dev then the base(target) branch can be master.

oh yeah that makes sense.  I was thinking that the PR should contain a keyword like 'release' or 'hotfix' or something like that, but your idea seems simpler.

2021-08-17 23:38 UTC, ryannowarm commented
Done

2021-11-15 19:02 UTC, merged